[tool.black]
line-length = 88
target-version = ["py310"]
include = '\\.(pyi?)$'
exclude = '''
/(
  |\.git
  |\.venv
  |env
  |venv
  |build
  |dist
  |__pycache__
  |migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 88
